/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkerHomeRouteImport } from './routes/worker.home'
import { Route as PassportSlugRouteImport } from './routes/passport.$slug'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminReviewIdRouteImport } from './routes/admin.review.$id'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerHomeRoute = WorkerHomeRouteImport.update({
  id: '/worker/home',
  path: '/worker/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportSlugRoute = PassportSlugRouteImport.update({
  id: '/passport/$slug',
  path: '/passport/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/admin/review',
  path: '/admin/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewIdRoute = AdminReviewIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminReviewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/status': typeof StatusRoute
  '/admin/review': typeof AdminReviewRouteWithChildren
  '/passport/$slug': typeof PassportSlugRoute
  '/worker/home': typeof WorkerHomeRoute
  '/admin/review/$id': typeof AdminReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/status': typeof StatusRoute
  '/admin/review': typeof AdminReviewRouteWithChildren
  '/passport/$slug': typeof PassportSlugRoute
  '/worker/home': typeof WorkerHomeRoute
  '/admin/review/$id': typeof AdminReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/status': typeof StatusRoute
  '/admin/review': typeof AdminReviewRouteWithChildren
  '/passport/$slug': typeof PassportSlugRoute
  '/worker/home': typeof WorkerHomeRoute
  '/admin/review/$id': typeof AdminReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/login'
    | '/otp'
    | '/profile'
    | '/status'
    | '/admin/review'
    | '/passport/$slug'
    | '/worker/home'
    | '/admin/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/login'
    | '/otp'
    | '/profile'
    | '/status'
    | '/admin/review'
    | '/passport/$slug'
    | '/worker/home'
    | '/admin/review/$id'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/login'
    | '/otp'
    | '/profile'
    | '/status'
    | '/admin/review'
    | '/passport/$slug'
    | '/worker/home'
    | '/admin/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  ProfileRoute: typeof ProfileRoute
  StatusRoute: typeof StatusRoute
  AdminReviewRoute: typeof AdminReviewRouteWithChildren
  PassportSlugRoute: typeof PassportSlugRoute
  WorkerHomeRoute: typeof WorkerHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/home': {
      id: '/worker/home'
      path: '/worker/home'
      fullPath: '/worker/home'
      preLoaderRoute: typeof WorkerHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/$slug': {
      id: '/passport/$slug'
      path: '/passport/$slug'
      fullPath: '/passport/$slug'
      preLoaderRoute: typeof PassportSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/admin/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review/$id': {
      id: '/admin/review/$id'
      path: '/$id'
      fullPath: '/admin/review/$id'
      preLoaderRoute: typeof AdminReviewIdRouteImport
      parentRoute: typeof AdminReviewRoute
    }
  }
}

interface AdminReviewRouteChildren {
  AdminReviewIdRoute: typeof AdminReviewIdRoute
}

const AdminReviewRouteChildren: AdminReviewRouteChildren = {
  AdminReviewIdRoute: AdminReviewIdRoute,
}

const AdminReviewRouteWithChildren = AdminReviewRoute._addFileChildren(
  AdminReviewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  ProfileRoute: ProfileRoute,
  StatusRoute: StatusRoute,
  AdminReviewRoute: AdminReviewRouteWithChildren,
  PassportSlugRoute: PassportSlugRoute,
  WorkerHomeRoute: WorkerHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
